config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  resources :users, only: :index do
    resource :profile, only: [:show, :edit, :update] do
      resources :skills, only: [:new, :create]
    end
    resources :profile_skills, only: [:destroy]
  end

  post 'users/:user_id/profile_skill/:profile_skill_id/evaluators/', to: 'evaluators#create', as: 'evaluators'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
# == Schema Information
#
# Table name: evaluations
#
#  id           :integer          not null, primary key
#  evaluated_id :integer
#  evaluator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Evaluation < ApplicationRecord
  belongs_to :evaluator, class_name: "User"
  belongs_to :evaluated, class_name: "ProfileSkill", counter_cache: "evaluations_count"
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :integer          not null, primary key
#  name         :string
#  introduction :text
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Profile < ApplicationRecord
  belongs_to :user

  has_many :profile_skills, dependent: :destroy
  has_many :skills, through: :profile_skills, source: 'skill'

  accepts_nested_attributes_for :skills
end

app/models/profile_skill.rb
# == Schema Information
#
# Table name: profile_skills
#
#  id                :integer          not null, primary key
#  profile_id        :integer
#  skill_id          :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  evaluations_count :integer          default("0")
#

class ProfileSkill < ApplicationRecord
  belongs_to :profile
  belongs_to :skill

  has_many :evaluations, foreign_key: "evaluated_id", dependent: :destroy
  has_many :evaluators, through: :evaluations, source: :evaluator
end

app/models/skill.rb
# == Schema Information
#
# Table name: skills
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Skill < ApplicationRecord
  has_many :profile_skills, dependent: :destroy
  has_many :profiles, through: :profile_skills, source: 'profile'

  # Validation
  # nameが存在する
  validates :name, presence: true, uniqueness: true
  # nameは英数字のみ
  validates :name, format: { with: /\A[a-zA-Z0-9]+\z/ }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  has_many :evaluations, foreign_key: "evaluator_id", dependent: :delete_all
  has_many :eval_skills, through: :evaluations, source: :evaluated
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def correct_user
    @user = User.find(params[:user_id])
    redirect_to root_path, alert: 'not correct user!' unless @user == current_user
  end
end

app/controllers/evaluators_controller.rb
class EvaluatorsController < ApplicationController

  def create
    # LinkからPostしているため、URLからparamsを取得する
    user = User.find(params[:user_id])
    skill_relation = ProfileSkill.find(params[:profile_skill_id])

    begin
      skill_relation.evaluators << user
      redirect_back fallback_location: root_path
    rescue ActiveRecord::RecordInvalid => e
      redirect_back fallback_location: root_path, alert: "save evaluation failed: #{e}"
    rescue ActiveRecord::RecordNotUnique => e
      redirect_back fallback_location: root_path, alert: "already save evaluator: #{e}"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_skills_controller.rb
class ProfileSkillsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def destroy
    user = current_user
    user_skill = ProfileSkill.find(params[:id])
    if user_skill.profile != user.profile
      return redirect_back fallback_location: root_path, alert: "no user error"
    end

    if user_skill.destroy
      redirect_back fallback_location: root_path, alert: "delete skill success"
    else
      redirect_back fallback_location: root_path, alert: "delete skill failure"
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @has_user_profile = @profile.present?

    @skill_relations = @profile.profile_skills.eager_load(:evaluators, :skill).order("evaluations_count desc")
  end

  def edit
    @user = current_user
    @profile = @user.profile
    @skill = Skill.new
    if @profile.nil?
      @profile = @user.profile = Profile.new
    end

    @skill_relations = ProfileSkill.where(profile: @profile).eager_load(:skill)
  end

  def update
    if current_user.profile.nil?
      current_user.profile = Profile.new(profile_params)
      check_and_redirect current_user.profile.save
    else
      check_and_redirect current_user.profile.update(profile_params)
    end
  end

  private

    def profile_params
      params.require(:profile).permit(
        :name,
        skills_attributes: [
          :id,
          :name
        ]
      )
    end

    def check_and_redirect exec
      if exec
        redirect_to edit_user_profile_path(@user), notice: 'save user profile success'
      else
        redirect_to edit_user_profile_path(@user), alert: 'save user profile failed'
      end
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @skill = Skill.new

    if @user.nil? or @user.profile.nil?
      redirect_to root_path, alert: "no exists such account"
    end
  end

  def create
    user = User.find(params[:user_id])

    begin
      skill = find_by_or_new_skill(skill_params)
      user.profile.skills << skill
      redirect_user_page user
    rescue ActiveRecord::RecordInvalid
      redirect_to user_profile_path(user), alert: "save skill failed"
    rescue ActiveRecord::RecordNotUnique
      redirect_to user_profile_path(user), alert: "not unique skill name"
    end
  end

  private

    def skill_params
      params.require(:skill).permit(:name)
    end

    def find_by_or_new_skill params
      skill = Skill.find_by(params)
      if skill
        return skill
      else
        return Skill.create!(params)
      end
    end

    def redirect_user_page user
      if user == current_user
        redirect_to edit_user_profile_path(user)
      else
        redirect_to user_profile_path(user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluators_helper.rb
module EvaluatorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_skills_helper.rb
module ProfileSkillsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/home/index.html.slim
/! Page Contents
.ui.masthead.center.aligned.vertical.segment
  .ui.text.container
    h1.ui.header
      | Demo-Profile-Page
    h2.ui
      | ナイスなプロフィールを書きましょう！
  .ui.container
    - if user_signed_in?
      = link_to "Get Started", edit_user_profile_path(current_user),
        class: "ui huge secondary inverted orange entry button"
    - else
      = link_to "Login or Sign up", user_session_path,
        class: "ui huge secondary inverted orange entry button"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ProfilePrototype
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - if notice
      .ui.message
        i.close.icon
        = notice
    - elsif alert
      .ui.warning.message
        i.close.icon
        = alert
    .pusher
      .ui.nav.container
        .ui.large.secondary.pointing.menu
          = link_to "Home", root_path, class: "a item"
          .right.item
            - if user_signed_in?
              .a.ui.span
              = link_to current_user.email, user_profile_path(current_user)
              = link_to "Sign out", destroy_user_session_path, method: :delete, class: "a ui basic button"
            - else
              = link_to "Log in", new_user_session_path, class: "a ui basic button"
              = link_to "Sign up", new_user_registration_path, class: "a ui basic button"

      .main.section
        .ui.main.container
          = yield

      - if Rails.env.development?
        .ui.container
          .ui.debug.segment
            = debug(params)

      .ui.footer.center.aligned.inverted.vertical.segment
        .ui.text.container
          h4.ui.inverted.header Footerは飾り。

    coffee:
      $(".message .close").on "click", () ->
        $(this)
          .closest ".message"
          .fadeOut "normal"

app/views/profiles/edit.html.slim
h3.ui.dividing.header プロフィールを編集する

.ui.form.group
  = form_for [@user, @profile], html: { class: "ui form" } do |f|
    .field
      = f.label :name, "名前"
      = f.text_field :name, placeholder: "Your name"
    = f.submit "名前を更新", class: "ui primary button"

  .ui.vertical.segment

  .field
    label スキル・特徴
  - @skill_relations.each do |skill_relation|
    .field
      .ui.right.labeled.input
        input placeholder="#{skill_relation.skill.name}"
        .ui.basic.label
          = link_to user_profile_skill_path(@user, skill_relation), :method => :delete do
            i.trash.outline.icon
  = form_for [@user, @profile, @skill],html: { class: "ui form" } do |f|
    .field
      = f.label :name, "新しくスキルを追加"
      = f.text_field :name, placeholder: "Your skill"
    = f.submit "スキルを追加", class: "ui primary button"

h3.ui.dividing.header プロフィールを確認する
= link_to "確認する", user_profile_path(@user), class: "ui button"

app/views/profiles/show.html.slim
- if @has_user_profile

  .ui.top.attached.header Profile
  .ui.attached.segment
    h3.ui.dividing.header
      = @user.profile.name
    p
    | ここに自己紹介を書く予定です。
  .ui.attached.header Skills
  .ui.attached.segment
    .ui.two.column.devided.grid
      .ui.container
        - @skill_relations.each do |relation|
          .ui.labeled.button
            = link_to relation.skill.name, evaluators_path(current_user, relation), method: :post, class: "ui basic skill button"
            .ui.basic.left.pointing.label
              = relation.evaluators.size
    - if @user != current_user
      = link_to "スキルを推薦する",  new_user_profile_skill_path(@user, @profile), class: "ui green basic button"
  - if @user == current_user
    .ui.attached.header Edit
    .ui.attached.segment
      = link_to "Profileを編集する", edit_user_profile_path(@user), class: "ui button"

- else

  h1.ui.dividing.header
    | ユーザープロフィールが存在しません。

app/views/skills/new.html.slim
h3.dividing.header
 = "#{@user.profile.name} さんにスキルを追加する"

= form_for [@user, @profile, @skill], html: { class: "ui form" } do |f|
  .field
    = f.text_field :name, placeholder: "Your name"

  = f.submit "スキルを追加", class: "ui primary button"